### PR TITLE
fix const in compute_intersection(of cells)

### LINKED ISSUE #11: Make sure arguments to compute_intersection (of cells) are const.

### PR DESCRIPTION
**Pull request by fdrmrc**
Fixes #11

### CODE REVIEW

File: source/compute_intersections.cc [hunk 1]
```diff
@@ -148,6 +144,10 @@ namespace dealii::NonMatching
 
     if (n_vertices_cell0 == 4 && n_vertices_cell1 == 4)
       { // rectangle-rectangle
+
+        std::swap(vertices_cell0[2], vertices_cell0[3]);
+        std::swap(vertices_cell1[2],
+                  vertices_cell1[3]); // to be consistent with dealii
```
Comment (luca-heltai) [inline source/compute_intersections.cc:150]: can you do this if it is const?

Comment (fdrmrc) [reply source/compute_intersections.cc:150]: Yes because in these lines I just swapped the vertices, and then the two vectors are given as const lvalue refs to the `compute_intersection_of_cells().`
